language: node_js
node_js:
  - "6"
before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
install:
  - npm install
script:
  - npm test
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
